version: '3'

services:
  app-blue:
    image: dhivyassnu/labexercise:latest
    container_name: app-blue
    ports:
      - "3001:3000"  # Blue instance mapped to port 3001
    environment:
      - NODE_ENV=production

  app-green:
    image: dhivyassnu/labexercise:latest
    container_name: app-green
    ports:
      - "3002:3000"  # Green instance mapped to port 3002
    environment:
      - NODE_ENV=production
